RegisterNetEvent('esx_healthnarmour:set')
AddEventHandler('esx_healthnarmour:set', function(health, armour)
  local playerPed = PlayerPedId()
  SetEntityHealth(playerPed, health)
  SetPedArmour(playerPed, armour)
end)

RegisterNetEvent('esx_healthnarmour:save')
AddEventHandler('esx_healthnarmour:save', function()
  local playerPed = PlayerPedId()
  TriggerServerEvent('esx_healthnarmour:update', GetEntityHealth(playerPed), GetPedArmour(playerPed))
end)